name: PhysxMc
version: '${version}'
main: com.kamesuta.physxmc.PhysxMc
api-version: 1.16
authors: [ Kamesuta ]

commands:
  rotationtest:
    description: Test command for rotation
    usage: /rotationtest
